### ISSUE TITLE
Clarification on setting local description with setLocalDescription()

### ISSUE THREAD

**Issue by rajukasaramoni** [paullouisageneau/libjuice#160] opened 2022-06-16 14:41 UTC
Hello Paul-Louis,

 I have referred to peerconnection.hpp APIs and example programs like copy-paste. In this we do not have way to send the negotiated offer description as local description with setLocalDescription () sort of API.  This setLocalDescription () does not take any input and it sets the description decided by the libdatachannel internally (some fields are hardcoded like sctp port). how to set the application decided (through negotiation with SIP) description like SCTP port, UDP port, fingerprint etc. Can you please help answering this.

**Comment by paullouisageneau** [comment] 2022-06-17 12:30
Duplicate of https://github.com/paullouisageneau/libdatachannel/issues/658

**Closed by paullouisageneau** 2022-06-17 12:30 UTC
Labels: duplicate
