### ISSUE TITLE
Connecting to web_webrtc takes 3 times the time in stun mode and in turn mode

### ISSUE THREAD

**Issue by LiuAriel** [paullouisageneau/libjuice#145] opened 2022-02-16 14:39 UTC
Currently using the library to connect to the web side, in the same LAN mode, the stun mode takes hundreds of milliseconds, and in the turn mode of different LANs, the time consumption can be close to 3s. In the same code environment, using libnice, the turn mode takes less time. It is more than 100 milliseconds than the stun mode. Through the current phenomenon, it is suspected that the program has not done a good job in dealing with the interactive process of turn!
look forward to your reply！

**Comment by paullouisageneau** [comment] 2022-02-16 20:25
Duplicate of https://github.com/paullouisageneau/libdatachannel/issues/559

**Closed by paullouisageneau** 2022-02-16 20:25 UTC
Labels: duplicate
