### ISSUE TITLE
No pair is selected if remote candidates arrive faster than the local one from STUN

### ISSUE THREAD

**Issue by mihaizh** [paullouisageneau/libjuice#85] opened 2021-03-31 13:05 UTC
Hello!

I write the issue here because even if I talk about the examples from `libdatachannel`, I guess this might be a problem related to `libjuice`. If not, I can rewrite the issue in `libdatachannel`.

I've compiled the `client` example application from `libdatachannel`. I also run the python signaling server on a public server. Then I run both clients on machines that are on different networks and try to create a connection between them by providing one with the id of the other. Both receive a `srflx` candidate from the STUN server with the public IP address, which I will call from now "remote candidate" and "local candidate".

The problem is that it won't find any valid pairs, even after the remote candidates have been added IF the local candidate coming from the STUN server arrived faster than the remote one. On the other hand, if the local one arrives after the remote candidate, everything works. Now, the entire application is asynchronous, meaning the local candidate and remote candidate can arrive in any order... and usually, the local candidate arrives faster, so most of the time the connection won't be opened.

From what I investigated, a valid pair is selected in `agent_bookkeeping` based on entries that have their state set to `ICE_CANDIDATE_PAIR_STATE_SUCCEEDED`, and this is set in `agent_process_stun_binding` based on entries that have their type set to `AGENT_STUN_ENTRY_TYPE_CHECK`. Now, these entries are added by `setRemoteCandidate` from `libdatachannel` and the function `agent_process_stun_binding` is called only when the agent receives data from the STUN server. Based on this, if the function `setRemoteCandidate` is called after the STUN server sent the candidate, the function `agent_process_stun_binding` will never be called again (because neither `agent_recv` will be called again since there's no more data from the STUN server) thus leading to not selecting any pair.

In `agent_add_remote_candidate`, I saw that there is a function `agent_interrupt`. Is this supposed to make sure the function `agent_process_stun_binding` is called after the candidate is added? Because if the answer is yes, it doesn't do its job.

Any idea on what should be done? Am I missing something?

**Comment by paullouisageneau** [comment] 2021-03-31 15:37
Thanks for reporting. I think your diagnostic mixes up the request to the STUN server and STUN probes between peers as both use the same STUN binding method. The function `agent_process_stun_binding` is also called when the agent receives a STUN request or response from the other peer, that's when it might mark a pair as succeeded. This probing mechanism is independant from the STUN server.

Could you please clarify the high-level non-working call sequence and provide the verbose log if possible?

**Comment by mihaizh** [comment] 2021-03-31 16:19
So, the application is the [datachannel-client](https://github.com/paullouisageneau/libdatachannel/tree/master/examples/client) example from `libdatachannel`. The only modification is that I hardcoded the STUN server. Nothing else.

Here are the logs when it does not work: 
[verbose_log_defect.txt](https://github.com/paullouisageneau/libjuice/files/6237943/verbose_log_defect.txt)

Here are the logs when it does work:
[verbose_log_working.txt](https://github.com/paullouisageneau/libjuice/files/6237946/verbose_log_working.txt)

Both are generated on the same setup, with a few minutes difference. I can manage to make it work "reliably" by putting a breakpoint on agent.c:1324 and when hit I wait for a few seconds before continuing.

Also, this is done in Windows 10.

**Comment by paullouisageneau** [comment] 2021-03-31 18:35
When it does not work, the issue is that the local peer does not get any response from the other peer.

There is a symptomatic behavior when it works, as the local peer sees responses coming from a peer reflexive address different from the remote server reflexive address (from the STUN server). My guess is the peers are behind non-cooperative NATs (endpoint-dependant basically) but one of them sometimes behaves cooperatively (possibly depending on the load).

What is the Internet access type of each peer?

**Comment by mihaizh** [comment] 2021-03-31 20:32
One of them is behind a router, and that's all, at least to my knowledge (from there is the ISP). The other one is on mobile tethering from my phone. Does not matter which is which, they have the same behavior, but when I generated the logs the offerer was on phone tethering and the answerer was on router Ethernet. Even both on my router does not work. My router acts like the Wi-Fi network and Ethernet network are on different networks. They do not communicate, so if I have one on Ethernet and one on Wi-Fi, they have the same behavior.

I tested with someone else too, which is on the other side of the town, and the exact same thing happens again. It uses the same ISP as me.

Not sure what to think. The fact that I put that breakpoint and it works, boggles me.

**Comment by mihaizh** [comment] 2021-04-01 09:39
I tested the [web](https://github.com/paullouisageneau/libdatachannel/tree/master/examples/web) client with somebody. We tried 5-10 times, it worked every time. We switched to the `datachannel-client`, it worked for 2-3 times, then it stopped working. We switched back to the browser, it didn't work either. Now nothing works, except for the `datachannel-client` if I do the thing with the breakpoint. If I do that, it works and I receive the hello message.

I don't get it.

**Comment by paullouisageneau** [comment] 2021-04-01 10:43
> One of them is behind a router, and that's all, at least to my knowledge (from there is the ISP). The other one is on mobile tethering from my phone. Does not matter which is which, they have the same behavior, but when I generated the logs the offerer was on phone tethering and the answerer was on router Ethernet. 

Mobile networks typically use carrier-grade NATs which implement an endpoint-dependent mapping (you might also encounter the former term "symmetric NAT"), and they are problematic for ICE. As a result the connectivity entirely relies on the other side not having this behavior, hence my suggestion that it could sometimes work with your landline ISP and sometimes not.

The symptoms you describe during your tests are coherent with your ISP using a big NAT which behavior is sometimes problematic. Do you know if you have a unique public address, or if you share one with multiple users?

> Even both on my router does not work. My router acts like the Wi-Fi network and Ethernet network are on different networks. They do not communicate, so if I have one on Ethernet and one on Wi-Fi, they have the same behavior.
 
If the router does not route one network to the other, it could be expected depending on how NAT is implemented. For instance if the WiFi is on secondary NAT itself on the Ethernet network, it requires the STUN server itself to be on the Ethernet network, a public STUN server would be useless.

> Not sure what to think. The fact that I put that breakpoint and it works, boggles me (probably because I do not fully understand how it works).

You are right, this is puzzling and might indicate that I'm wrong with my previous explanation (which is good because then it might be fixable). Does it always work when you change the timing with the breakpoint?

**Comment by mihaizh** [comment] 2021-04-01 11:41
I did another round of testings on the same setup as last time, with the tethering network from my phone and the Ethernet connection. The web client works every time. It just works. But the `datachannel-client` works only with the breakpoint set. The trick with the breakpoint does not work consistently. But, once every few tries it does. Probably depends on my timing.

**Comment by paullouisageneau** [comment] 2021-04-01 11:51
OK, could you give me the logs from both sides when it doesn't work ? I'll investigate.

**Comment by mihaizh** [comment] 2021-04-01 12:22
Here are the logs with edited IPs. It should be easy to reason about them because I put them as `[OFFERER_PUBLIC_IP]` and `[ANSWERER_PUBLIC_IP]`.
[log_verbose_offerer_ethernet.txt](https://github.com/paullouisageneau/libjuice/files/6243379/log_verbose_offerer_ethernet.txt)
[log_verbose_answerer_tethering.txt](https://github.com/paullouisageneau/libjuice/files/6243380/log_verbose_answerer_tethering.txt)

Not sure if I share the IP addresses.

**Comment by paullouisageneau** [comment] 2021-04-01 12:43
Thank you for the logs, I think it's fine without the addresses. Just a question: when you tested the web client, was it with the same STUN server? The STUN server is deployed on a different public address, right?

**Comment by mihaizh** [comment] 2021-04-01 12:58
Yes, you are right. It's the exact same STUN server and is deployed on a server from Linode.

**Comment by paullouisageneau** [comment] 2021-04-02 17:46
@mihaizh Another question, what are the other networks both peers are connected to? Are there some kind of VPN access?

**Comment by mihaizh** [comment] 2021-04-02 17:55
There's no VPNs active. One of them has VPN installed, but it is offline.

If you're talking about the other private IP addresses, then some of them are from Virtual Box/VMware networking adapters, WSL adapters, and one of them has the network adapter of the VPN, but I checked and it was disabled.

**Comment by paullouisageneau** [comment] 2021-04-02 18:00
OK thanks.

**Comment by paullouisageneau** [comment] 2021-04-03 13:37
I merged a few fixes on master, mostly pending stuff, probably not related though. You can still try on your side to be sure.

There is not a lot to work on in the log of the failing scenario, as the only visible symptom is that no peer ever receives any response from the remote one. The impact the breakpoint on `agent.c:1324` (on `v0.7.0`) or `agent.c:1350` (on `master`) could have is still unclear to me. Do you confirm the breakpoint is non-conditional?
https://github.com/paullouisageneau/libjuice/blob/2f492fb697c802a21c1f4855b598ec5f2bbfce6e/src/agent.c#L1350

The breakpoint is on STUN binding response either from the server or from the peer. When the response is from the server, the breakpoint is set after the candidate callback is called, which is done just before in `agent_add_local_reflexive_candidate()`:
https://github.com/paullouisageneau/libjuice/blob/2f492fb697c802a21c1f4855b598ec5f2bbfce6e/src/agent.c#L1346

So either the response from the STUN server comes first, in which case the breakpoints pauses *after* the local srflx candidate is emitted and sent to the remote peer, or the first response from the remote peer comes first, in which case it will work anyway since no response is ever received in the failing scenario. This means the breakpoint has no effect on the order between the emission of the local srflx candidate and the reception of the remote one. Maybe I am missing something here?

Therefore, it seems to me that the only effect the breakpoint could have is a side effect: it will stop the agent thread after emitting the local server reflexive and delay the following requests to the remote peer, possibly all of them if the STUN server answers faster than the STUN pacing time of 50ms. However, it's still unclear to me how sending requests to the other peer too early could result in no more messages going through.

**Comment by paullouisageneau** [comment] 2022-02-15 17:58
I'm closing this, please reopen if the problem still exists.

**Closed by paullouisageneau** 2022-02-15 17:58 UTC
