### ISSUE TITLE
 agent.c:777: Failed to interrupt thread by triggering socket, errno=99

### ISSUE THREAD

**Issue by Philonous** [paullouisageneau/libjuice#79] opened 2021-03-10 21:02 UTC
Hey!

I wanted to use libjuice in a personal project but noticed some error messages; I'm getting ` agent.c:777: Failed to interrupt thread by triggering socket, errno=99` on every call of 
`juice_add_remote_candidate()` and `juice_destroy()`. The connection establishment seems to work fine despite the warnings; however, trying to destroy the agent hangs my program (OTOH your client seems to not suffer from that problem, so that might be a bug on my end)

The problem seems to also exist in the tests executable, built on Linux (I tried NixOS 20.09 and Ubuntu 20.04).

How to reproduce:
* Freshly clone repository
* run `make`
* run `./tests`

**Comment by paullouisageneau** [comment] 2021-03-11 09:03
The library sends datagrams to its own socket in order to interrupt the thread waiting on it with `select()` (this is to my knowledge the only portable manner to do so). In your case, it seems `sendto()` to localhost address fails with errno `EADDRNOTAVAIL`. 

Strangely, this errno is not documented as a possible return value for `sendto()`. I guess it could mean IPv6 is enabled but the loopback does not have an IPv6 address, it's definitely a corner case the library does not handle.

Do you have IPv6 enabled? If so, does `$ ping ::1` work on your system?

**Comment by Philonous** [comment] 2021-03-11 09:28
Ipv6 is disabled on my system:

```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
```
And the loopback device doesn't have an ipv6 address either. 

`ping ::1` returns `ping: connect: Cannot assign requested address`

Re-enabling ipv6 stops the error from occuring on my host, but it's still present within a docker container that doesn't have an ipv6 address

**Comment by paullouisageneau** [comment] 2021-03-11 10:51
OK, I can reproduce with `net.ipv6.conf.all.disable_ipv6 = 1`, which in particular removes the IPv6 on `lo`. The problem was that the library assumed it would be present provided the host supports IPv6.

The issue is fixed by https://github.com/paullouisageneau/libjuice/pull/80

**Comment by Philonous** [comment] 2021-03-11 11:19
https://github.com/paullouisageneau/libjuice/pull/80/commits/afd4a20bfe6e70add8817a3ec9418de2b3075f3b fixes the problem for me. 

Thanks a bunch!

**Closed** 2021-03-11 11:51 UTC
